### ISSUE TITLE
Mac OS X docker client 1.2.0 is generating 'panic: runtime error: index out of range'

### ISSUE THREAD

**Issue by yhuang** [boot2docker/osx-installer#64]
`# Mac OS X 10.9.4`

```
$ docker
panic: runtime error: index out of range

goroutine 16 [running]:
runtime.panic(0x3a96e0, 0x60297c)
    /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
main.main()
    /go/src/github.com/docker/docker/docker/docker.go:99 +0x9ff

goroutine 17 [runnable]:
runtime.MHeap_Scavenger()
    /usr/local/go/src/pkg/runtime/mheap.c:507
runtime.goexit()
    /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 18 [runnable]:
bgsweep()
    /usr/local/go/src/pkg/runtime/mgc0.c:1976
runtime.goexit()
    /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 19 [runnable]:
runfinq()
    /usr/local/go/src/pkg/runtime/mgc0.c:2606
runtime.goexit()
    /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 20 [runnable]:
os/signal.loop()
    /usr/local/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
    /usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x32
```

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
